/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./SpendLimit.client";
export declare namespace contracts {
    const SpendLimit: {
        SpendLimitQueryClient: typeof _1.SpendLimitQueryClient;
    };
}
//# sourceMappingURL=index.d.ts.map