/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export type Uint64 = string;
export interface InstantiateMsg {
    price_resolution_config: PriceResolutionConfig;
    tracked_denoms: TrackedDenom[];
}
export interface PriceResolutionConfig {
    quote_denom: string;
    staleness_threshold: Uint64;
    twap_duration: Uint64;
}
export interface TrackedDenom {
    denom: string;
    swap_routes: SwapAmountInRoute[];
}
export interface SwapAmountInRoute {
    pool_id: number;
    token_out_denom: string;
    [k: string]: unknown;
}
export type QueryMsg = {
    spending: {
        account: string;
        authenticator_id: Uint64;
    };
} | {
    spendings_by_account: {
        account: string;
    };
};
export type Timestamp = Uint64;
export type Uint128 = string;
export interface SpendingResponse {
    spending: Spending;
}
export interface Spending {
    last_spent_at: Timestamp;
    value_spent_in_period: Uint128;
}
export interface SpendingsByAccountResponse {
    spendings: [Uint64, Spending][];
}
//# sourceMappingURL=SpendLimit.types.d.ts.map